### ISSUE TITLE
Node version bump to 9.4.0

### ISSUE THREAD

**Issue by bengro** [Surnet/alpine-node-wkhtmltopdf#6]
Would you consider bumping node to 9.4.0?

**Comment by chdanielmueller** [comment]
I'm working on a build with alpine 3.6 which is the underlaying image for node 9.4.0 and 8.9.4 LTS.
Had a working build yesterday.
I will update this issue as soon as I have published the version.

**Comment by bengro** [comment]
Awesome stuff, thanks!

**Comment by chdanielmueller** [comment]
Hi @bengro,

I replaced the creation logic for the Dockerfiles with a bash script and moved everything to a new repo.
Please see https://github.com/Surnet/docker-wkhtmltopdf

The version you would like is `surnet/alpine-node-wkhtmltopdf:9.4.0-0.12.4-small`.
If you have any questions, concerns or inputs for the new repo please tell me.

Thanks,
Daniel

**Comment by bengro** [comment]
Great stuff. Thank you!
